### ISSUE TITLE
Make it look better on iPads?

### ISSUE THREAD

**Issue by hckiang** [yuetyam/canim#1]
First of all thank you for this amazing free app! I have one problem on iPad: the size of the keyboard on iPad looks a bit odd. Below is some comparison between Canim and the built-in iOS keyboard on iPad 2019. I'm wondering is there any chance this could be fixed? :)

**First two pictures**: the floating keyboard. How to open it: choose any iOS built-in keyboard, use the two finger pinch to "zoom out" the keyboard, then switch to Canim. Then you can see that Canim is too high compared to the built-in. Also, if we start from the default big keyboard mode of Canim, the two finger pinching doesn't work (so everytime I want the floating keyboard I'll have to switch to the iOS default keyboard, "zoom out", and switch back to Canim).

**Third and fourth picture**: on iPad portrait mode, built-in vs Canim. The font of Canim is a bit too small, making it looks a bit uncomfortable (not a big problem, though).

**Fifth and sixth picture**: landscape mode, built-in vs Canim. The font of Canim becomes worse compared to the built-in. (or the aspect ratio just feels wrong? IDK but it doesn't look as good)

![photo_2020-07-23_15-06-11](https://user-images.githubusercontent.com/5366447/88289822-1e43c380-ccf6-11ea-8e1e-5acd8c7d699a.jpg)
![photo_2020-07-23_15-06-22](https://user-images.githubusercontent.com/5366447/88289832-20a61d80-ccf6-11ea-9d22-9b970618ee3a.jpg)

![photo_2020-07-23_15-06-18](https://user-images.githubusercontent.com/5366447/88289828-1f74f080-ccf6-11ea-8924-69a2b34934b7.jpg)
![photo_2020-07-23_15-06-20](https://user-images.githubusercontent.com/5366447/88289830-200d8700-ccf6-11ea-9f80-cdfa67ecf98a.jpg)

![photo_2020-07-23_15-06-15](https://user-images.githubusercontent.com/5366447/88289827-1f74f080-ccf6-11ea-8d97-6865ee2b2647.jpg)
![photo_2020-07-23_15-16-44](https://user-images.githubusercontent.com/5366447/88290765-8b0b8d80-ccf7-11ea-905c-88ffa9711db1.jpg)

**Comment by ososoio** [comment]
Hello! 
Thank you for your very helpful feedback.

I never have tested this keyboard on a real iPad since I don't have one. I thought the **Floating Keyboard** feature is system keyboard only, so didn't pay any attention to that. Big mistake.

The UI things of this keyboard is base on the iPhone, it is predictable this keyboard works very bugly on iPad.

For the pass months, I have been focus on combining this keyboard with the IME engine [`Rime`](https://github.com/rime/librime) , and there is not much progress. That's why this keyboard didn't get any updates / bug fixes so long. (Another reason is I'm not very familiar with programming :) 

I'm refactoring this project with iOS 14. We will have a major update after or maybe before iOS 14 released. I hope the behaviors on iPad will be quite better at that time.

The new source code would be hosted on [`yuetyam/jyutping`](https://github.com/yuetyam/jyutping) , you can *Watch -> Release only* for notifications. And this repository will be archived.

Thank you for this issue again, any further suggestions or feedback would be greatly appreciated.

**Comment by ososoio** [comment]
Hello, @hckiang 

Thank you for your very helpful feedback.

I never have tested this keyboard on a real iPad since I don't have one. I thought the **Floating Keyboard** feature is system keyboard only, so didn't pay any attention to that. Big mistake.

The UI things of this keyboard is base on the iPhone, it is predictable this keyboard works very bugly on iPad.

For the pass months, I have been focus on combining this keyboard with the IME engine [`Rime`](https://github.com/rime/librime) , and there is not much progress. That's why this keyboard didn't get any updates / bug fixes so long. (Another reason is I'm not very familiar with programming :) 

I'm refactoring this project with iOS 14. We will have a major update after or maybe before iOS 14 released. I hope the behaviors on iPad will be quite better at that time.

The new source code would be hosted on [`yuetyam/jyutping`](https://github.com/yuetyam/jyutping) , you can *Watch -> Release only* for notifications. And this repository will be archived.

Thank you for this issue again, any further suggestions or feedback would be greatly appreciated.

**Comment by ososoio** [comment]
Hi, @hckiang 

A new version just available on the App Store, with some updates on iPad, have a try.

My iPad simulator shows the floating keyboard can be trigger on the top and bottom blank areas of the keyboard, I will continue do some work on this problem.

![screenshot1](https://user-images.githubusercontent.com/44096493/88623940-9fc19a00-d0d8-11ea-939a-bf23ea9047b9.png)

Thank you

**Comment by hckiang** [comment]
Thanks a lot for your help! Now it’s much better on the iPad! :)
